// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by scripts/generateProducts.mjs

export const GENERATED_PRODUCTS = [
  {
    "id": 1,
    "name": "Apple"
  },
  {
    "id": 2,
    "name": "Banana"
  },
  {
    "id": 3,
    "name": "Orange"
  },
  {
    "id": 4,
    "name": "Grape"
  },
  {
    "id": 5,
    "name": "Bicycle"
  },
  {
    "id": 6,
    "name": "Samsung S5"
  },
  {
    "id": 7,
    "name": "Toy Train"
  },
  {
    "id": 8,
    "name": "Cup of coffee"
  },
  {
    "id": 9,
    "name": "Chair"
  },
  {
    "id": 10,
    "name": "TV"
  }
] as const;
