// scripts/generateProducts.mjs
import fs from 'node:fs/promises';
import https from 'node:https';

const API_URL = 'https://hoff.is/store2/api/v1/product/list';
const OUT_FILE = 'tests/config/generatedProducts.ts';

/**
 * Very small helper to GET JSON via HTTPS without extra dependencies.
 */
function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        let data = '';

        res.on('data', chunk => (data += chunk));
        res.on('end', () => {
          try {
            resolve(JSON.parse(data));
          } catch (err) {
            reject(new Error('Failed to parse JSON from API: ' + err.message));
          }
        });
      })
      .on('error', reject);
  });
}

async function main() {
  console.log(`Fetching product list from: ${API_URL}`);

  let responseData;

  try {
    responseData = await fetchJson(API_URL);
  } catch (err) {
    console.error(`❌ Failed to fetch product list: ${err.message}`);
    process.exit(1);
  }

  // Handle different possible API shapes
  let products = responseData.products ?? responseData;

  if (!Array.isArray(products)) {
    console.error('❌ Unexpected API response shape:', responseData);
    process.exit(1);
  }

  // Extract only id + name (if available)
  const normalized = products
    .map((p) => {
      if (typeof p === 'number') return { id: p, name: undefined };
      if (typeof p === 'object' && p.id != null) return { id: p.id, name: p.name };
      return null;
    })
    .filter(Boolean);

  if (normalized.length === 0) {
    console.error('❌ No valid products found in API response.');
    process.exit(1);
  }

  // Generate the file content
  const fileContent =
    `// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.\n` +
    `// Generated by scripts/generateProducts.mjs\n\n` +
    `export const GENERATED_PRODUCTS = ${JSON.stringify(normalized, null, 2)} as const;\n`;

  try {
    await fs.writeFile(OUT_FILE, fileContent, 'utf8');
    console.log(`✅ Successfully wrote product list to ${OUT_FILE}`);
  } catch (err) {
    console.error('❌ Failed to write file:', err.message);
    process.exit(1);
  }
}

main();
